# Generated by Django 3.2 on 2021-04-17 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CourseCategory', '0002_coursedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('detail', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(upload_to='Products')),
                ('price', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('qty', models.BigIntegerField(blank=True, default=1, null=True)),
                ('CourseCategory_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CourseCategory.coursecategory')),
            ],
        ),
    ]
