# Generated by Django 3.2 on 2021-04-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseCategory', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='CourseCategory_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
    ]
