# Generated by Django 3.2 on 2021-04-17 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CourseCategory', '0006_coursecategory_coursedetail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CourseCategory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseCategory.coursecategory'),
        ),
    ]
