# Generated by Django 3.2 on 2021-04-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseCategory', '0007_alter_product_coursecategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='pdf',
            field=models.ImageField(blank=True, null=True, upload_to='course-files'),
        ),
    ]
