# Generated by Django 3.2 on 2021-04-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseCategory', '0008_alter_coursedetail_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='course-files'),
        ),
    ]
