# Generated by Django 3.2 on 2021-04-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseCategory', '0009_alter_coursedetail_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course-images'),
        ),
    ]
