# Generated by Django 3.2 on 2021-04-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseCategory', '0010_coursedetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
