# Generated by Django 3.2 on 2021-04-14 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='UserProfile')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Authentication.customuser')),
                ('user_type', models.CharField(choices=[('STD', 'student'), ('TEC', 'teacher'), ('ADM', 'admin')], default='STD', max_length=3)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
