# Generated by Django 3.2 on 2021-06-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_quizpoint_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizpoint',
            name='feedback',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
